version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: blog_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kiemphongkim
      MYSQL_USER: kiemphongkim
      MYSQL_PASSWORD: kiemphongkim
    ports:
      - "1234:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
